### ISSUE TITLE
Bug in Code

### ISSUE THREAD

**Issue by bcndanos** [o0ragman0o/LibCLLi#2]
There's an error in the line 46:

```
    function exists(CLL storage self) internal constant returns (bool) {
        if (self.cll[HEAD][NEXT] != NULL || self.cll[HEAD][NEXT] != NULL)
            return true;
    }
```

The NEXT has to be changed to PREV. It should be:

```
    function exists(CLL storage self) internal constant returns (bool) {
        if (self.cll[HEAD][PREV] != NULL || self.cll[HEAD][NEXT] != NULL)
            return true;
    }
```

But it can be refactored as:

```
    function exists(CLL storage self) internal constant returns (bool) {
        return (self.cll[HEAD][PREV] != NULL || self.cll[HEAD][NEXT] != NULL);
    }
```

I saw the copy of this module in the ITT repository is already ok.

**Comment by o0ragman0o** [comment]
Thanks heaps for the heads up.  I'd forgotten to push that repo.  I need to set up solidity import paths better otherwise I end up in this situation needing to copy source into local folders rather than just reference it from their native repos.

Note the filename change LibCLLi.sol -> LibCLL.sol.  I was using 'i' to indicate 'index' but as there are 'unit' and 'int' versions of the library there was a confusing name clash.
